Repository zilong-yang/360-seating, pull requests merged in 2021-06, with the labels that each got.

#33 Navigation Buttons and Order State
  client/public/index.html
  client/public/styles/navbutton.css
  client/src/App.js
  client/src/Components/BackButton.js
  client/src/Components/MovieBrowser.js
  client/src/Components/MovieDisplay.js
  client/src/Components/NextButton.js
  client/src/Components/TicketCounter.js
  client/src/Components/TicketSelection.js
  client/src/services/Movies.js
Labels: UI, api, frontend, task

#39 More Comprehensive Nav Buttons
  client/public/styles/movieDisplay.css
  client/public/styles/seatSelection.css
  client/src/App.js
  client/src/Components/BackButton.js
  client/src/Components/MovieBrowser.js
  client/src/Components/NextButton.js
  client/src/Components/SeatSelection.js
  client/src/Components/SeatTile.js
  client/src/Components/TicketCounter.js
  client/src/Components/TicketSelection.js
  client/src/services/Theaters.js
  server/controllers/theaterController.js
  server/routes/theaterRoutes.js
Labels: api, backend, frontend, task

#44 Refine ticket selection page
  client/public/styles/seatSelection.css
  client/src/Components/SeatSelection.js
  client/src/Components/SeatTile.js
Labels: DB, movie seat, task

#45 Frontend and Backend Functions to Change Seat Availability
  client/src/Components/SeatSelection.js
  client/src/services/Theaters.js
  server/controllers/theaterController.js
  server/package-lock.json
  server/package.json
  server/routes/theaterRoutes.js
  server/server.js
Labels: api, backend, frontend, task
