Repository zilong-yang/360-seating, pull requests merged in 2021-07, with the labels that each got.

#60 Checkout page
  client/package-lock.json
  client/public/index.html
  client/public/styles/checkout.css
  client/src/App.js
  client/src/Components/Checkout.js
  client/src/Components/SeatSelection.js
  client/src/Components/TicketSelection.js
Labels: frontend, task, transaction

#71 Order Summary Page
  .gitignore
  backendTester.http
  client/public/index.html
  client/public/styles/navbutton.css
  client/public/styles/orderSummary.css
  client/src/App.js
  client/src/Components/BackButton.js
  client/src/Components/Checkout.js
  client/src/Components/NextButton.js
  client/src/Components/OrderSummary.js
  client/src/services/Orders.js
  server/controllers/orderController.js
  server/models/Order.js
  server/routes/orderRoutes.js
  server/server.js
Labels: DB, UI, api, backend, frontend, task

#72 Backdrop
  client/public/index.html
  client/public/styles/backdrop.css
  client/public/styles/checkout.css
  client/public/styles/movieDisplay.css
  client/public/styles/orderSummary.css
  client/public/styles/seatSelection.css
  client/src/App.js
  client/src/Components/Backdrop.js
  client/src/Components/Checkout.js
  client/src/Components/OrderSummary.js
  client/src/Components/SeatSelection.js
  client/src/Components/TicketSelection.js
Labels: UI
